manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Shtaiven
      url-base: https://github.com/Shtaiven
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: nice-view-fairyboard
      remote: Shtaiven
      revision: zmk-v0.2 # tag compatible with 0.3
  self:
    path: config
